# Generated by Django 4.2.17 on 2024-12-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_latestexchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rate_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('FLEXIBLE', 'Flexible')], default='FIXED', max_length=10),
        ),
    ]
