# Generated by Django 4.2.17 on 2025-01-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_bid_contact_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
