# Generated by Django 4.2.17 on 2024-12-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
