# Generated by Django 4.2.17 on 2024-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
