# Generated by Django 4.2.17 on 2024-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting Response'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='AWAITING', max_length=10),
        ),
    ]
