# Generated by Django 4.2.17 on 2025-01-01 22:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0007_remove_bid_is_accepted_bid_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('user', 'offer')},
        ),
    ]
